title: "Karthik Chauhan"
#logo: "assets/img/logo.jpg"
description: >
  Data Scientist | Data Analyst | Software Developer | M.Sc in Big Data Analytics | Bridging Software Development and Data Analytics.<br>
  
  <strong>Education:</strong><br>
  &bull;Master's degree in Big Data Analytics from St. Xavier's College, Mumbai.<br>
  &bull;Bachelorâ€™s degree in Computer Science from University of Mumbai.
  
repository: false  # Disables the link to the repository
footer_text: "This project is maintained by Karthik Chauhan"
theme: jekyll-theme-minimal
include: ["_assets"]
